import Head from 'next/head';
import type { AppProps } from 'next/app';

import { Global } from '@emotion/react';
import globalStyles from '@/common/styles/globalStyles';
import theme from '@/common/styles/themes/main';

import AuthProvider from '@/auth/providers';
import ThemeProvider from '@/common/providers/theme';
import AlertsProvider from '@/common/providers/alerts';

import useAppLoading from '@/common/hooks/useAppLoading';

import Loader from '@/common/components/Loader';

const App = ({ Component, pageProps }: AppProps) => {
  const { loading } = useAppLoading();
  return (
    <AlertsProvider>
      <AuthProvider>
        <ThemeProvider theme={theme}>
          <Head>
            <title>Helpers</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Global styles={globalStyles} />
          {loading && <Loader />}
          <Component {...pageProps} loading={loading} />
        </ThemeProvider>
      </AuthProvider>
    </AlertsProvider>
  );
};

export default App;
