import Head from 'next/head';
import type { AppProps } from 'next/app';

import { Global } from '@emotion/react';
import globalStyles from '@/styles/globalStyles';

import AuthProvider from '@/providers/auth';

import useAppLoading from '@/hooks/useAppLoading';

import Loader from '@/components/common/Loader';

const App = ({ Component, pageProps }: AppProps) => {
  const { loading } = useAppLoading();
  return (
    <AuthProvider>
      <Head>
        <title>Helpers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Global styles={globalStyles} />
      {loading && <Loader />}
      <Component {...pageProps} loading={loading} />
    </AuthProvider>
  );
};

export default App;
